export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SET_USERNAME = 'SET_USERNAME';
export const SET_HOME_CONTENT = 'SET_HOME_CONTENT';

export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';

export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';

export const APPLY_FILTERS = 'APPLY_FILTERS';

export const GET_EDITIONS = 'GET_EDITIONS';

export const START_TRACKING = 'START_TRACKING';
export const START_TRACKING_SUCCESS = 'START_TRACKING_SUCCESS';

export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';

export const ADD_PROGRESS = 'ADD_PROGRESS';
export const ADD_PROGRESS_SUCCESS = 'ADD_PROGRESS_SUCCESS';

export const GET_MY_BOOKS = 'GET_MY_BOOKS';
export const GET_MY_BOOKS_SUCCESS = 'GET_MY_BOOKS_SUCCESS';

export const GET_REVIEWS_FOR_BOOK = 'GET_REVIEWS_FOR_BOOK';

export const ADD_REPLY = 'ADD_REPLY';
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS';

export const ADD_EDITION = 'ADD_EDITION';

export const PUBLISH_BOOK = 'PUBLISH_BOOK';

export const CREATE_BOOKLIST = 'CREATE_BOOKLIST';

export const GET_BOOKLISTS = 'GET_BOOKLISTS';
export const GET_BOOKLISTS_SUCCESS = 'GET_BOOKLISTS_SUCCESS';

export const GET_BOOKLIST_CONTENT = 'GET_BOOKLIST_CONTENT';
export const GET_BOOKLIST_CONTENT_SUCCESS = 'GET_BOOKLIST_CONTENT_SUCCESS';

export const DELETE_BOOK_FROM_BOOKLIST = 'DELETE_BOOK_FROM_BOOKLIST';

export const RESET_CURRENT_LIST_CONTENT = 'RESET_CURRENT_LIST_CONTENT';

export const ADD_BOOKS_TO_BOOKLIST = 'ADD_BOOKS_TO_BOOKLIST';
