export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SET_USERNAME = 'SET_USERNAME';
export const SET_HOME_CONTENT = 'SET_HOME_CONTENT';

export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';

export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';

export const APPLY_FILTERS = 'APPLY_FILTERS';

export const GET_EDITIONS = 'GET_EDITIONS';

export const START_TRACKING = 'START_TRACKING';
export const START_TRACKING_SUCCESS = 'START_TRACKING_SUCCESS';

export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';